### ISSUE TITLE
Consider using a more liberal license like MIT?

### ISSUE THREAD

**Issue by justindujardin** [Guillemdb/fragile#5]
I think your project looks really promising, thanks for sharing! 👏 💯 

I work on an open-source RL library that solves math problems (https://mathy.ai), and I'd like to try integrating your fragile swarm into it (as an alternative to its existing MCTS training.) Sadly, I can't use it with the GPL license because it would restrict usage severely in commercial contexts.

I wonder if you'd be willing to consider a more liberal license like MIT or Apache2?

Either way, thanks for publishing this work, it's such a cool approach!

**Comment by Guillemdb** [comment]
Thanks :) I really liked your project, it looks very promising. 

Releasing it under a more permissive license is something that I am considering if there are enough people willing to use this framework. Specially if I get some help combining FAI with RL algorithms.

I will be finishing the remaining features that are pending to be uploaded, and once the first release is ready I will seriously consider changing the license (as long as my colleagues are ok with it)

**Comment by justindujardin** [comment]
@Guillemdb that's awesome to hear, I'm glad you'll consider it. I'm happy to help out by integrating this into Mathy. I'll close this issue for now 👍
